# Generated by Django 2.0.7 on 2018-07-08 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.Categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.TextField(blank=True),
        ),
    ]
